export function Question1() {
    this.load.image(
        'Question1:answer',
        require('../../assets/daily_reward/quiz/question/backgrounds/answer_background.png')
    )
    this.load.image(
        'Question1:back',
        require('../../assets/daily_reward/quiz/question/buttons/btn_back.png')
    )
    this.load.image(
        'Question1:question',
        require('../../assets/daily_reward/quiz/question/text/txt_question.png')
    )
    this.load.image(
        'Question1:smallPlank',
        require('../../assets/daily_reward/quiz/question/backgrounds/small_plank.png')
    )
    this.load.image(
        'Question1:substraction',
        require('../../assets/daily_reward/quiz/question/icons/icon_circle.png')
    )
    this.load.image(
        'Question1:Vines',
        require('../../assets/daily_reward/quiz/question/backgrounds/vines.png')
    )
    this.load.image(
        'Question1:Vraag',
        require('../../assets/daily_reward/quiz/question/text/txt_question_schrijf_van_vijf.png')
    )
}
