export function QuizAnswer() {
    this.load.image(
        'QuizAnswer:plank',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/daily_reward_plank-1@2x.png')
    )
    this.load.image(
        'QuizAnswer:plank2',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/daily_reward_plank-2@2x.png')
    )
    this.load.image(
        'QuizAnswer:plank3',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/daily_reward_plank-3@2x.png')
    )
    this.load.image(
        'QuizAnswer:plank4',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/daily_reward_plank-4@2x.png')
    )
    this.load.image(
        'QuizAnswer:plank5',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/daily_reward_plank@2x.png')
    )
    this.load.image(
        'QuizAnswer:correct',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/btn_quiz_correct-4@2x.png')
    )
    this.load.image(
        'QuizAnswer:btnDown',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/btn_arrow_down@2x.png')
    )
    this.load.image(
        'QuizAnswer:rewardPlank',
        require('../../assets/daily_reward/quiz/daily_reward_quiz_finish_answers/daily_reward_plank_down.png')
    )
}
