export const _ITEMS = [
    {
        id: 0,
        name: 'Item',
        category: 'shirt',
        price: 25,
        requiredLevel: 1,
        asset: require('./assets/character/clothings/shirts/tshirt_variant_blank.png'),
    },
    {
        id: 1,
        name: 'Item',
        category: 'shirt',
        price: 100,
        requiredLevel: 1,
        asset: require('./assets/character/clothings/shirts/shirt_long_variant_blank.png'),
    },
    {
        id: 2,
        name: 'Item',
        category: 'shirt',
        price: 80,
        requiredLevel: 1,
        asset: require('./assets/character/clothings/shirts/tshirt_variant_circle.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/character/clothings/shirts/shirt_long_variant_circle.png'),
    },
    {
        id: 4,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/character/clothings/shirts/tshirt_variant_squares.png'),
    },
    {
        id: 5,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/character/clothings/shirts/shirt_long_variant_squares.png'),
    },
    {
        id: 6,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/character/clothings/shirts/tshirt_variant_stripes.png'),
    },
    {
        id: 7,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/character/clothings/shirts/shirt_long_variant_stripes.png'),
    },

    // PANTS
    {
        id: 8,
        name: 'Item',
        category: 'pants',
        price: 10,
        requiredLevel: 1,
        asset: require('./assets/character/clothings/pants/pants_variant_blank.png'),
    },
    {
        id: 9,
        name: 'Item',
        category: 'pants',
        price: 10,
        requiredLevel: 1,
        asset: require('./assets/character/clothings/pants/pants_long_variant_blank.png'),
    },
    {
        id: 10,
        name: 'Item',
        category: 'pants',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/character/clothings/pants/pants_variant_worn.png'),
    },
    {
        id: 11,
        name: 'Item',
        category: 'pants',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/character/clothings/pants/pants_long_variant_worn.png'),
    },
    {
        id: 12,
        name: 'Item',
        category: 'pants',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/character/clothings/pants/pants_variant_damaged.png'),
    },
    {
        id: 13,
        name: 'Item',
        category: 'pants',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/character/clothings/pants/pants_long_variant_damaged.png'),
    },
];
