export const _ITEMS = [
    {
        id: 0,
        name: 'Item',
        category: 'shirt',
        price: 25,
        requiredLevel: 1,
        asset: require('./assets/clothing/items/item-1.png'),
    },
    {
        id: 1,
        name: 'Item',
        category: 'shirt',
        price: 100,
        requiredLevel: 1,
        asset: require('./assets/clothing/items/item-2.png'),
    },
    {
        id: 2,
        name: 'Item',
        category: 'shirt',
        price: 80,
        requiredLevel: 1,
        asset: require('./assets/clothing/items/item-3.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 3,
        asset: require('./assets/clothing/items/item-4.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/clothing/items/item-5.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/clothing/items/item-6.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/clothing/items/item-7.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/clothing/items/item-8.png'),
    },
    {
        id: 3,
        name: 'Item',
        category: 'shirt',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/clothing/items/item-9.png'),
    },
];
