export const _ITEMS = [
    {
        id: 0,
        name: 'Item',
        price: 25,
        requiredLevel: 1,
        asset: require('./assets/clothing/items/shirt_short/shirt_stripes.png'),
    },
    {
        id: 1,
        name: 'Item',
        price: 100,
        requiredLevel: 1,
        asset: require('./assets/clothing/items/shirt_long/shirt_blank.png'),
    },
    {
        id: 2,
        name: 'Item',
        price: 80,
        requiredLevel: 1,
        asset: require('./assets/clothing/items/shirt_short/shirt_blank.png'),
    },
    {
        id: 3,
        name: 'Item',
        price: 10,
        requiredLevel: 3,
        asset: require('./assets/clothing/items/shirt_long/shirt_circle.png'),
    },
    {
        id: 3,
        name: 'Item',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/clothing/items/shirt_long/shirt_circle.png'),
    },
    {
        id: 3,
        name: 'Item',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/clothing/items/shirt_short/shirt_circle.png'),
    },
    {
        id: 3,
        name: 'Item',
        price: 10,
        requiredLevel: 5,
        asset: require('./assets/clothing/items/shirt_long/shirt_circle.png'),
    },
    {
        id: 3,
        name: 'Item',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/clothing/items/shirt_short/shirt_squares.png'),
    },
    {
        id: 3,
        name: 'Item',
        price: 10,
        requiredLevel: 10,
        asset: require('./assets/clothing/items/shirt_short/shirt_squares.png'),
    },
];
